# Generated by Django 5.2.4 on 2025-09-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_old',
            field=models.ImageField(blank=True, default='media/defaults/default_old.png', null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_teenager',
            field=models.ImageField(blank=True, default='media/defaults/default_teenager.png', null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_young',
            field=models.ImageField(blank=True, default='media/defaults/default_young.png', null=True, upload_to='pictures'),
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
