# Generated by Django 5.2.4 on 2025-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0003_user_history_user_picture_old_user_picture_teenager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_old',
            field=models.ImageField(blank=True, default='defaults/default_old.png', null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_teenager',
            field=models.ImageField(blank=True, default='defaults/default_teenager.png', null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_young',
            field=models.ImageField(blank=True, default='defaults/default_young.png', null=True, upload_to='pictures'),
        ),
    ]
