# Generated by Django 5.2.4 on 2025-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0004_alter_user_picture_old_alter_user_picture_teenager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
